# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160529_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modified',
            new_name='updated',
        ),
    ]
